### ISSUE TITLE
Finish NFC implementation

### ISSUE THREAD

**Issue by conorpp** [solokeys/solo#1]
* [ ] Custom antenna
* [ ] AMS 3956 driver

**Comment by merlokk** [comment]
I know a guy who can help with antenna design
https://www.upwork.com/o/profiles/users/_~01ebbfa9e6b4a9119b/
If it needs)

**Comment by manuel-domke** [comment]
I can also help with antenna design verification and testing.
As I'm part of your crowd already, feel free to reach out. I can at least support by providing some measurements for design verification.

**Comment by acerspyro** [comment]
Apologies for the possibly dumb question, but does that mean I'll have to buy the hardware again once this is completed to get NFC support?

NFC does not appear to be working on my SoloKey, and I stumbled upon this issue.

**Comment by conorpp** [comment]
Yes it is 2 different hardware models.  The NFC version has 2 main hardware changes:

* AS3956 for NFC communication
* Antenna/coil

The firmware is mostly done (thanks a lot to @merlokk) and the antenna design/tuning is almost done.

**Comment by conorpp** [comment]
Please contact hello@solokeys.com for store/order related questions.

**Comment by bbigras** [comment]
I was also under the impression that NFC was already supported. It would be a good idea to make it clear on https://shop.solokeys.com/ that it's not the case yet and mention if the current hardware will support it or not.

**Comment by merlokk** [comment]
https://github.com/solokeys/solo/commits/nfc

**Comment by conorpp** [comment]
@bbigras @acerspyro thanks for the feedback.  Definitely not our intent to mislead people on this.  We just updated our store to note current tokens don't support NFC.

**Comment by conorpp** [comment]
:D
