### ISSUE TITLE
Solo key emulation

### ISSUE THREAD

**Issue by andy-dicki** [solokeys/solo#130]
Solo key emulator (which is detected as Solo key) might be needed for developers who don't have Solo key.
Update: it means Solo key which will work in browser and other applications.

**Comment by nickray** [comment]
related: https://github.com/solokeys/solo/issues/122

you could also try to port to a different cortex m4 that has a QEMU, e.g. STM32F429I-Discovery (https://gnu-mcu-eclipse.github.io/qemu/)

**Comment by conorpp** [comment]
For development I think it's easiest for now to use the UDP bridge to the PC build.  @andy-dicki have you tried it?

```
cd solo/
make
./main
```

```
python tools/ctap_test.py sim u2f
```

Testing/developing JS APIs could be done with Node.

**Comment by andy-dicki** [comment]
Will firmware flashing work for it?

**Comment by conorpp** [comment]
I'm not sure what you mean.  It is building the firmware, but for your PC, and then running it directly.  The source is the same for both, expect `device.c` and `crypto.c` are different.

**Comment by andy-dicki** [comment]
I mean, _emulate_ device, not protocol.

**Comment by conorpp** [comment]
Okay, I just suggest since it can work well for development without a solo, as I often use it.

**Comment by nickray** [comment]
@andy-dicki there are no plans to emulate solo device on pc, this is completely out of scope. for this, you might look into QEMU.

**Comment by conorpp** [comment]
Closing since a good solution is presented in #131
