### ISSUE TITLE
(venv) solo key verify returns error if PIN is set

### ISSUE THREAD

**Issue by ghost** [solokeys/solo#139]
If PIN is set, solo key verify in venv returns ValueError: PIN required! but does not ask for it.

**Comment by stappersg** [comment]
(breaking silence after a half year)

What is supposed to be done with this issue?

If the various _thumbs up_ on the original post mean something like
> you reporting expected behaviour

then say so  **and** close this issue.

**Comment by nickray** [comment]
Wrong repo, but solo-python did gain a `--pin` argument.
