### ISSUE TITLE
Recommended update: Firmware version 2.0.0

### ISSUE THREAD

**Issue by nickray** [solokeys/solo#140]
For further information, see https://github.com/solokeys/solo/issues/125#issuecomment-471234042 and https://github.com/solokeys/solo/issues/113.

To update to the ~~alpha~~ new stable version 2.0.0:

```
pip3 install -U solo-python

# secure
solo key update --secure --alpha
# hacker
solo key update --hacker --alpha
```
**OR**: visit https://update.solokeys.com

If you want or have to do this, be aware that as noted in https://github.com/solokeys/solo/releases/tag/2.0.0, **"...if you're upgrading from 1.1.0 or 1.1.1, AND you've used your key to authenticate to services, then those services may need to be re-registered. This is due to the counter decreasing."**

Happy to collect feedback here ~~before we roll out to everyone~~.

**Comment by nickray** [comment]
Report from @fooflington:

> @nickray @conorpp thanks, apologies – to report state after upgrading to 2.0.0 (should this be a separate issue?):
> 
> GitLab worked (no reregistration required)
> Google needed re-registering
> GitHub needed re-registering
> Dropbox worked fine
> Facebook worked fine

**Comment by nickray** [comment]
Report from @webs86:

> @conorpp I have updated my solo key to 2.0.0 and update fix issue with gitlab. I didn't have to re-register my key

**Comment by cstuder** [comment]
Updated to 2.0.0 with a Solokey USB-A:

GitHub worked fine
Dropbox worked fine

(Using Chrome 72 on Windows 10)

**Comment by ukscone** [comment]
> Updated to 2.0.0 with a Solokey USB-A:
> 
> GitHub worked fine

> 
> (Using Chrome 72 on Windows 10)

i'm being dense and can't find out how to get a solokey working with github. all it seems to offer me is a phone app or sms. Any chance you could write up the steps in words of one syllable so i can under stand it please :)

**Comment by nickray** [comment]
You're not dense :) A lot of sites only let you use U2F as 2FA **after** setting up SMS or TOTP first. The thinking is probably that they're scared users will lock themselves out, leading to angry users and/or support requests.

The process for GitHub: https://help.github.com/en/articles/configuring-two-factor-authentication

You can find more deep links to instructions here: https://krypt.co/start/?noredirect=true

**Comment by conorpp** [comment]
Thanks for feedback everyone.  Latest firmware is now `2.2.2`.  If you have any more issues, please report.
