### ISSUE TITLE
Unable to register key

### ISSUE THREAD

**Issue by cfasnacht** [solokeys/solo#141]
I'm unable to register my solo keys.
I have two solo keys, with the firmware versions:
1.1.1 and 2.0.0 (which I updated because of the Gitlab Issue)

If I try to register my key with Github the following error appears.
"This device cannot be registered."

I tried with Firefox 65.0.1 and Chromium 72.0.3626.121

I have a yubikey 4 which works in both browsers.

**Comment by conorpp** [comment]
To confirm, you tried with the 2.0.0 version?  Gitlab works on the same browser + operating system?

I'm not able to replicate on Chrome 72.0.3626.121.

**Comment by cfasnacht** [comment]
No both Github and Gitlab don't work, I was never able to register one of the keys successfully.

**Comment by conorpp** [comment]
Which firmware file did you use to update?  Hacker or Secure?  If you have a "hacker" edition key, and you update with a secure build, then it will cause this issue

**Comment by cfasnacht** [comment]
@conorpp No I don't have the hacker versions and I upgraded one of the keys with: solo key update --secure to 1.1.1 and the other solo key update --secure --alpha to 2.0.0
solo key verify output for both keys:
Please press the button on your Solo key
Register valid
Valid Solo Secure firmware from SoloKeys

**Comment by conorpp** [comment]
Does the LED turn orange?  what operating system are you on?

**Comment by cfasnacht** [comment]
No the led is green. Ubuntu 18.04.2 LTS

**Comment by conorpp** [comment]
Okay, so when you start a register request, it appears nothing happens on the key?

**Comment by cfasnacht** [comment]
Yes the led just continues to dim up and down in green

**Comment by conorpp** [comment]
So when you run `solo key verify`, you don't press the button?  It just works?

**Comment by cfasnacht** [comment]
No I have to press the button otherwise this error is displayed.
Please press the button on your Solo key
Error getting credential, is your key in bootloader mode?
Try: `solo program aux leave-bootloader`

**Comment by conorpp** [comment]
Does it work without `sudo`?

**Comment by conorpp** [comment]
If you haven't already, please install the udev rules for Linux:

This should work:
https://docs.solokeys.io/solo/udev/

These rules are ideal for everything (reading logs, programming, etc).
https://github.com/solokeys/solo/tree/master/udev

**Comment by cfasnacht** [comment]
Thanks for your help with the udev rule it works.
