### ISSUE TITLE
Work once one time on Manjaro

### ISSUE THREAD

**Issue by rafaelmr2** [solokeys/solo#146]
Hi,

I configure some services with solokey on Manjaro (github, nextcloud, tutanota). I put the udev files and was working. When I tried again (after reboot), didn't work anymore. 

```
$ udevadm monitor --environment --udev | grep DEVNAME
DEVNAME=/dev/bus/usb/001/014
DEVNAME=/dev/usb/hiddev0
DEVNAME=/dev/hidraw2
DEVNAME=/dev/bus/usb/001/014
```

when I insert solokey (the first time was hidraw0). When I press the button nothing happens. Lookin at `dmesg` shows the message below when I press the button:

```
[ 1993.487134] atkbd serio0: Unknown key pressed (translated set 2, code 0x8d on isa0060/serio0).
[ 1993.487139] atkbd serio0: Use 'setkeycodes e00d <keycode>' to make it known.
```

I updated to firmware 2.0.0 too and the problem persists.

Can you help me? Thanks for you work!!!

**Comment by conorpp** [comment]
What are you expecting to happen when you press the button?  Is there a FIDO request from your browser?

**Comment by nickray** [comment]
@rafaelmr2 maybe your udev rule is lacking the leading `SUBSYSTEM=="hidraw"`? I updated https://docs.solokeys.io/solo/udev/ to hopefully clarify. If you think your udev is correct, you can maybe see more info if you run `pip3 install -U solo-python --user` and see what commands like `solo ls`, `solo key wink` and `solo key verify` do.

**Comment by rafaelmr2** [comment]
> What are you expecting to happen when you press the button? Is there a FIDO request from your browser?

Yes, when the service request.

**Comment by rafaelmr2** [comment]
> @rafaelmr2 maybe your udev rule is lacking the leading `SUBSYSTEM=="hidraw"`? I updated https://docs.solokeys.io/solo/udev/ to hopefully clarify.
> 
> If you think your udev is correct, can you try `pip3 install -U solo-python --user` and see what commands like `solo ls`, `solo key wink` and `solo key verify` do?

It's working with new udev file. 

Thanks!!!
