### ISSUE TITLE
Invalid CBOR in GetInfo response

### ISSUE THREAD

**Issue by agl** [solokeys/solo#170]
Just poking at this device with Chrome, after flashing firmware 2.1.0:

Chrome rejects the GetInfo response because the CBOR is invalid and thus treats this firmware revision as U2F-only. Specifically, the entries in the CBOR map are incorrectly ordered. See [section 6](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#ctap2-canonical-cbor-encoding-form) on ordering.

**Comment by conorpp** [comment]
Thanks for reporting.  I just pushed a fix for this and tested Chrome is able to register+auth with FIDO2 without falling back to U2F.

Do you have a hacker/reprogrammable Solo and would be able to test on your side?  If so, you can update with my fix.

[solo.hex.zip](https://github.com/solokeys/solo/files/3065116/solo.hex.zip)

```
pip3 install python-solo
unzip solo.hex.zip
solo program bootloader solo.hex
```

**Comment by 0x0ece** [comment]
Good catch! Just tested this new firmware on Safari 12.1, the future is passwordless :)

<img width="721" alt="Screen Shot 2019-04-10 at 8 58 49 PM" src="https://user-images.githubusercontent.com/1491992/55929872-9ce52200-5bd3-11e9-822c-87d7f5fd3e05.png">

**Comment by agl** [comment]
> Do you have a hacker/reprogrammable Solo and would be able to test on your side? If so, you can update with my fix.

I have one on order.
