### ISSUE TITLE
 Solo Webupdate out of date

### ISSUE THREAD

**Issue by YakBizzarro** [solokeys/solo#178]
The webupdate site says

"SITE FIRMWARE OUT OF DATE!
Please inform SoloKeys!
Firmware flashing deactivated."

**Comment by 0x0ece** [comment]
Thank you, fixing soon. If you need to update in the meantime you can use the cli `solo key update --hacker` or `solo key update --secure`. Latest version is 2.2.0

**Comment by 0x0ece** [comment]
Fixed, thanks again!
