### ISSUE TITLE
Firmware won't boot when built with Debian buster toolchain

### ISSUE THREAD

**Issue by DanielG** [solokeys/solo#193]
When the firware is built on Debain buster the resulting binaries seem to not boot at all. The device does not even enumerate i.e. doesn't show up in dmesg.

I tried the same build steps with the ARM binary toolchain (`gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2`) which works.

I wouild like to get solo working with the Debian toolchain, any pointers on where in the code tricky bits that might depend on GCC versions are hiding would be appreciated.

Also the hardware docs still seem a bit sparse, is there a hardware serial console I can 
use to debug pre-usb boot? 

Build recipe used:

```
$ cd targets/stm32l432
$ make full-clean
$ make build-hacker
$ solo program bootloader solo.hex
``` 

Git commit: 1f3db3fe51cc6232f744930ebbf859285c0ba73c (Fix image in README)

GCC Version:
```
$ /usr/bin/arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Binutils Version:
```
$ /usr/bin/arm-none-eabi-ld --version
GNU ld (2.31.1-12+11) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by nickray** [comment]
These are bugs in the Debian toolchain, there is a related issue "somewhere".
