### ISSUE TITLE
The user presence check fails if the button is pressed after 2-3 seconds

### ISSUE THREAD

**Issue by rgerganov** [solokeys/solo#201]
I am using Chrome on Ubuntu 18.04 and I am playing with https://webauthn.me/. On this website there is 15 seconds timeout for the user presence check (i.e. pressing the button). I noticed that it succeeds only if the button is pressed immediately (2-3 seconds) after the browser prompt. Is this an intentional behavior?
I believe the root cause for this is that the device doesn't send CTAPHID_KEEPALIVE every 100ms as the [spec](https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-client-to-authenticator-protocol-v2.0-rd-20180702.html#usb-hid-keepalive) says.

**Comment by conorpp** [comment]
I believe this has been fixed.  U2F previously held the response until button was pressed (which caused timeout after 2-3 seconds).  Now it responds immediately, and the platform polls until real timeout (15s) or button is pressed.
