### ISSUE TITLE
Different behaviour for Facebook login on Firefox and Chrome

### ISSUE THREAD

**Issue by armsp** [solokeys/solo#203]
I received my SoloKey today (I am a total beginner to this technology) and for starters I decided to enable 2FA on my Facebook account (using Firefox). I was able to do that successfully. However I am **not** able to login to my account via Firefox because Firefox shows the following screen after I enter my username and password -
![Screenshot_2019-06-04 Facebook](https://user-images.githubusercontent.com/12681262/58903586-6cc58580-8723-11e9-956b-4d27b483af73.png)
Pressing the button on the key doesn't do anything as expected.  

On the other hand with Chrome I get the following and it works -
![Screenshot from 2019-06-04 23-45-17](https://user-images.githubusercontent.com/12681262/58903677-9d0d2400-8723-11e9-9121-3661f7bbb905.png)
My preferred browser is actually Firefox. Any idea how do I make Firefox work the same way as Chrome ?
My OS is Ubuntu. I have already setup the udev rules as well as the corresponding fields are set to True in Firefox.

**Comment by youiopmop** [comment]
In Firefox U2F is disabled by default, to enable it you need to go to `about:config` in Firefox and change `security.webauth.u2f` from false to true.

Some websites like GitHub say you need to use Chrome for U2F, but it works fine by changing your user-agent just for the site, you can do that by using something like `general.useragent.override.github.com` in about:config and putting a chrome user-agent there.

**Comment by armsp** [comment]
@youiopmop  as I had already mentioned, I had already set the fields to `true`, as a matter of fact, they are set to `true` by default on latest versions of Firefox. 
> I have already setup the udev rules as well as the corresponding fields are set to True in Firefox.  

Following is my current setup that still doesn't work the way its supposed to -
![image](https://user-images.githubusercontent.com/12681262/59005110-d9cb3f00-8839-11e9-9024-6a463598e944.png)

**Comment by JackGruber** [comment]
@armsp 

* Add `general.useragent.override.facebook.com` as new setting
* Use `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36` as value

for Github this works fine.

**Comment by armsp** [comment]
@JackGruber thanks a lot. It works as expected after the changes.
