### ISSUE TITLE
Add ability to reset resident keys

### ISSUE THREAD

**Issue by conradev** [solokeys/solo#207]
As discussed in #156, there should be a way to reset all resident keys on the device. This is mainly because I will be using my personal key for a lot of testing in bringing up FIDO2 stacks wherever I need them.

**Comment by conorpp** [comment]
The resident keys can all be reset by using the FIDO2 reset command.  On Windows, you can do this by going to the security key settings.  Or you can use our `solo-python` tool to send the reset.

```
solo key reset
```
