### ISSUE TITLE
Problem while using NFC on a Solo USB C key

### ISSUE THREAD

**Issue by chripell** [solokeys/solo#223]
Hello, I am backer 2105. Everything looks great, there is just a
little problem: the Solo TAP USB-C I've received doesn't work via NFC
on a Pixel Phone (generation 1 small). I'm pretty sure there is a bug
because I did the following experiments:

1) The same Solo TAP USB-C works when connected via USB-C both on the
same phone and on a laptop.

2) I've used the neat NXP application to locate the sweet spot for the
Solo. This also means that it is actually recognized and identified as
a U2F app (from the app output).

3) Another key I purchased, a SOLO TAB USB-A, works perfectly via NFC
on the same Pixel Phone.

4) I tried to check if there are updates available on Solo webupdate
but nothing.

5) I tried to re-enroll the key, just in case. But still it doesn't
work.

I would guess the information sent via NFC to Google Authenticator is
somehow wrong.

I tried to reach you by email hello@solokeys.com, but no answer.

**Comment by conorpp** [comment]
Hey @chripell, sorry for the delay.  We very likely sent a faulty USB-C model -- please follow up on the email you sent, we likely lost track of it.  Thanks!
