### ISSUE TITLE
update.solokeys.com not showing latest version? (2.4.0)

### ISSUE THREAD

**Issue by youiopmop** [solokeys/solo#225]
hiya, so i saw that there was the new solo release 2.4.0 under the 'releases' tab of the github, but https://update.solokeys.com/ still shows 2.3.0 as the latest version?

**Comment by nickray** [comment]
right, thanks, that was forgotten. should be fixed now.

**Comment by nickray** [comment]
right, thanks, that was forgotten. should be fixed now.
