### ISSUE TITLE
Programming all.hex on solokey hacker with solo program dfu required -d

### ISSUE THREAD

**Issue by sbweeden** [solokeys/solo#272]
When programming with both the bootloader+firmware I was following the instructions on https://docs.solokeys.io/solo/building/

After the command:
`solo program dfu all.hex`

my key did not turn on. I found that to get it to work I needed to use:
`solo program dfu -d all.hex`

Is this a known issue? Perhaps its as simple as updating the documentation or providing slightly different documentation when using the solokey hacker vs the NUCLEO board?

**Comment by conorpp** [comment]
This is the intended behavior, but wasn't really documented.  I added better documentation here:
https://docs.solokeys.io/solo/bootloader-mode#dfu

Once it's switched in DFU mode, it stays there until explicitly told to boot again.  It's a bit of a safety measure in case you program something bad, you have a chance to reprogram it before trying to boot a brick.

The `-d` stands for detach, and indicates to boot out of DFU mode automatically like what you were originally expecting.
