### ISSUE TITLE
Does Solo Hackers Key work with Windows Hello?

### ISSUE THREAD

**Issue by gkauraneja** [solokeys/solo#294]
I have updated my solo key to firmware version 2.4.3. 
 I am trying to register solo key on Microsoft Azure but it throws an exception when i add this as a security key device. Is it supported?

**Comment by aseigler** [comment]
It should work. Try this first:

![paste](https://user-images.githubusercontent.com/6605560/63893490-4b89d380-c9b8-11e9-9743-bb358687b56a.png)

**Comment by gkauraneja** [comment]
Thanks!! Closing this query.
