### ISSUE TITLE
Run security audit tools on code base

### ISSUE THREAD

**Issue by conorpp** [solokeys/solo#3]
I don't have much experience with this but it would be nice to run some static/dynamic analysis security tools on the code base.

**Comment by 0x0ece** [comment]
Valgrind would also be a good one to run, primarily to avoid mem leaks.

**Comment by pjz** [comment]
I suggest setting up CI to do this, so they'll get run with every change.

**Comment by MattMattV** [comment]
Alsoan audit performed by humans may be relevant to this project (:

**Comment by jacobalberty** [comment]
More hardware than software related but when I get my tokens in I'll be x-raying them. Would you be interested in copies of the x-rays?

**Comment by MattMattV** [comment]
I'll appreciate that ! (Even if I will be unable to see anything "wrong")

Thanks for the answer !

Le sam. 6 oct. 2018 à 20:16, Jacob Alberty <notifications@github.com> a
écrit :

**Comment by conorpp** [comment]
@jacobalberty Hell yeah!
