### ISSUE TITLE
FAQ about the key

### ISSUE THREAD

**Issue by treble2019** [solokeys/solo#338]
I recently purchased a couple of solokeys and very satisfied!!

From [1] there are two remarks:

> First, it generates a device-specific attestation key, which makes it trackable cross-domain. 

> Second, it only stores up to 8 registrations

Could you please comment if these limitations are fixed in the solokeys or how should I deal with these?

Many thanks for a fantastic product.

[1] https://github.com/hillbrad/U2FReviews#-u2f-zero

**Comment by conorpp** [comment]
These are for U2F-Zero.  For SoloKeys, registrations are unlimited, and attestation keys are now "batch" generated.  So same attestation key is used per 100K units of a particular model.
