### ISSUE TITLE
Example fails since last commit

### ISSUE THREAD

**Issue by gaetanww** [solokeys/solo#34]
The Readme states: 
> Run example client software. This runs through a registration and authentication.  `python python-fido2/examples/credential.py`

#33 broke this. I think it's because make is not calling
```Makefile
python-fido2: venv
	cd python-fido2/ && ../venv/bin/python setup.py install
```

**Comment by conorpp** [comment]
Thanks.  I just updated the README.  Run `cd python-fido2/ && python setup.py install` to install.

I removed it from Makefile since it's been annoying to force virtual-environments.
