### ISSUE TITLE
what is the ctap_encode_der_sig() used for?

### ISSUE THREAD

**Issue by bling206** [solokeys/solo#357]
Hi 

I am tracing about the solo's source code.
Why does the signature need to be used after the ctap_encode_der_sig() from instead of using directly the output from crypto_ecc256_sign().

Thank you!

**Comment by nickray** [comment]
There are two ways to serialize NIST P-256 signatures: encoding (r, s) as consecutive 32-byte arrays interpreted as big-endian integers (this is what `micro-ecc` outputs), or ASN.1 DER format ("SEQUENCE" of two, followed by two "INTEGER"s), which is what this encoding function does. CTAP uses COSE (https://tools.ietf.org/html/rfc8152), which specifies the latter format.

**Comment by nickray** [comment]
"Well actually" :D 
https://github.com/w3c/webauthn/issues/799 I guess at some point the intent may have been to use COSE, which would specify the raw format, whereas by "ossification" ASN.1 DER needs to be used.

**Comment by bling206** [comment]
Got it!! Thank you very much!!

**Comment by jolo1581** [comment]
Can this issue be closed?

**Comment by jolo1581** [comment]
Think we can close this issue, right?
