### ISSUE TITLE
SoloKey USB A on Windows 10

### ISSUE THREAD

**Issue by joshwalters12** [solokeys/solo#372]
I have just bought a SoloKey, and when I connect to my Ubuntu laptop, it works fine, but when I connect to my Windows 10 PC, it does not detect the device. However, when I load the program USB device tree viewer (https://www.uwe-sieber.de/usbtreeview_e.html), the pc then detects the key, but if i unplug, then re plug when the program is still running, it needs a refresh to then detect the device.

**Comment by joshwalters12** [comment]
Okay, so I've figured out this is an issue with my PC, not the SoloKey.

**Comment by conorpp** [comment]
Thanks for reporting, could you share what the issue was?  In case someone else runs into something similar.
