### ISSUE TITLE
Layout easy-to-solder board

### ISSUE THREAD

**Issue by conorpp** [solokeys/solo#4]

**Comment by corbolais** [comment]
hey conor,
thanks for your work on u2fa zero and the new project solo.

can help w/ schematics (cleanup etc.) and layout.

cheers

**Comment by dkanada** [comment]
If you have svg files of the buton icon used on the housing I would also like to submit some alternative styles. It doesn't seem like the icon is used anywhere else yet but the letter looks a bit odd jutting out of the edge of the design in my opinion.

**Comment by corbolais** [comment]
sry can't help you w/ svg files.

**Comment by conorpp** [comment]
@corbolais Yeah totally!  I'll post Eagle schematic and layout details soon.

@dkanada yes, seeing some other styles would be great.  We still have time to update the case if we find something we like.  Attached is the SVG I used.

[logo.zip](https://github.com/SoloKeysSec/solo/files/2473518/logo.zip)
