### ISSUE TITLE
Kickstarter is over

### ISSUE THREAD

**Issue by reedy** [solokeys/solo#40]
https://github.com/SoloKeysSec/solo#how-do-i-get-one is therefore out of date meaning https://solokeys.com/preorder/ is the only way to buy one now

Docs need an update :)

**Comment by conorpp** [comment]
Thanks, we will update this soon :)  Currently pretty swamped with fulfilling KS orders

**Comment by reedy** [comment]
Good to hear (you're busy)!

Slightly offtopic... Any idea what the post kickstart preorder shipping delays look like? Obviously as the page says, the solo tap are coming later... But I'm wondering about ordering a few of the various types to be delivered to an address in the US for me to pick up in late Jan/early Feb and save me some tax/vat/import hassle :)

**Comment by stappersg** [comment]
The https://github.com/SoloKeysSec/solo#how-do-i-get-one (note the **Sec**) redirects to https://github.com/solokeys/solo#how-do-i-get-one which is just https://github.com/solokeys/solo

Please close this issue.  Asking @reedy for help  (because issue reporters can close the issues they reported)
