### ISSUE TITLE
Bug when getting credentials metadata

### ISSUE THREAD

**Issue by rgerganov** [solokeys/solo#403]
If we try to get credential metadata and there are no resident keys on the device, it returns `FIDO_ERR_NO_CREDENTIALS`. This is not the correct behavior. We should return 0 existing and 50 remaining keys.

Will submit a patch shortly. /cc @conorpp

**Comment by rgerganov** [comment]
I found this issue when testing with the security manager in Google Chrome and then found 3 more issues, see the second commit in the PR.

Many thanks to @My1 for providing debug logs from a key that works with Chrome :)

**Comment by My1** [comment]
no problem, I wanna help solo too, also to show how helpful it is to have updates on a key. (maybe even the ppl with proprietary keys will notice someday that it's useful to not have them on full lockdown), lol
