### ISSUE TITLE
out of bounds error on 50th RK filled

### ISSUE THREAD

**Issue by My1** [solokeys/solo#407]
okay this is a weird one

precondition:
50th Residential slot filled (the th is no mistake, deleting earlier credentials doesnt seem to affect this)

trigger:
list credentials using solokeys/solo-python#71 or chrome

effect:
~~~
[CP] CP map has 2 elements
[CP] CP_pinProtocol
[CP] CP_subCommand
[CP] CP_cmdGetKeyAgreement
[CP] CP map has 4 elements
[CP] CP_pinProtocol
[CP] CP_subCommand
[CP] CP_keyAgreement
[CP] CP_pinHashEnc
[CP] CP_cmdGetPinToken
[MC] RP Begin @0.  1 total.
[CRED_MGMT] Get RP 0
[ERR] src/device.c:817: Out of bounds reading index 50 for rk
[ERR] src/device.c:817: Out of bounds reading index 50 for rk
[ERR] src/device.c:817: Out of bounds reading index 51 for rk
[ERR] src/device.c:817: Out of bounds reading index 51 for rk
[ERR] src/device.c:817: Out of bounds reading index 52 for rk
[ERR] src/device.c:817: Out of bounds reading index 52 for rk
[ERR] src/device.c:817: Out of bounds reading index 53 for rk
[ERR] src/device.c:817: Out of bounds reading index 53 for rk
~~~
and so on, basically lists every number twice and just increases in rapid succession. device becomes unresponsive until powercycle. (can be seen especially well on somu as it no longer turns blue upon touch)

tested using 4.0.0 with button skip provided by @conorpp
if the first credential (index 0) is deleted begin @0 as well as Get RP 0 become 1 instead. otherwise the same.

**Comment by conorpp** [comment]
This should be fixed now
