### ISSUE TITLE
Signing updates with my own key

### ISSUE THREAD

**Issue by davedoesdev** [solokeys/solo#422]
Hi-

Would it be possible to sign updates using my own key?

I guess I'd have to change [pubkey_boot](https://github.com/solokeys/solo/blob/91584538308f0f0906c988e6dd9ca1583e1e41d1/targets/stm32l432/bootloader/pubkey_bootloader.c#L3).

Do you have details of how you sign your updates?

Thanks

David

**Comment by rgerganov** [comment]
See PR #400

**Comment by davedoesdev** [comment]
Excellent, thanks
