### ISSUE TITLE
Solokey from Kickstarter and Azure AD

### ISSUE THREAD

**Issue by TimBobkov** [solokeys/solo#461]
Hi all.
It's not an issue just question. At the beginning Solokey from Kickstarter can't be used for AAD login. Does firmware update fix this?

**Comment by aseigler** [comment]
Yes, it works for AAD registration/login but not without firmware update.  Flash it to the latest and you'll be good to go.

**Comment by TimBobkov** [comment]
Thanks a lot, will try
