### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by robcypher** [solokeys/solo#473]
I'm facing the below error while trying to build from source as mentioned in the official documentation. Yields the below output [error]:

user@host:/tmp/solo/targets/stm32l432$ make firmware
make -f build/application.mk VERSION_FULL=4.0.0-15-gb86f0ee  -j8 solo.hex PREFIX= DEBUG=0 
make[1]: Entering directory '/tmp/solo/targets/stm32l432'
make[1]: *** No rule to make target 'solo.elf', needed by 'solo.hex'.  Stop.
make[1]: Leaving directory '/tmp/solo/targets/stm32l432'
make: *** [Makefile:17: firmware] Error 2

**Comment by whosnorman** [comment]
Heyo I'm hitting the same error, do you remember how were you able to resolve it?
