### ISSUE TITLE
I forgot my pin and now my key is blocked

### ISSUE THREAD

**Issue by emdouglas2001** [solokeys/solo#487]
Hi,
 As the subject says, I forgot my pin and now my key is blocked, is there way to unblock it.

Many Thanks

**Comment by jolo1581** [comment]
Use solo python.

I think the command is:
solo key reset

But this will also delete all credentials and connected sites

**Comment by conorpp** [comment]
Yes for any FIDO key this means you need to reset it, and will loose all of your credentials.  You can use our solo-python client to do so, or use the Security Key tool in Chrome settings.  You can also do it in Windows security key settings.

**Comment by emdouglas2001** [comment]
Thanks Guys,
That sorted my problem.
Many Thanks from a much happier Scotsman

**Comment by svn2208** [comment]
Is it possible to remove the pin again?

**Comment by nickray** [comment]
You can only remove the PIN by resetting it.
