### ISSUE TITLE
Applying Solokeys on LUKS

### ISSUE THREAD

**Issue by kagamineryuki** [solokeys/solo#491]
Hi, I recently bought this Solokeys and want to use the solokeys as second factor for my LUKS encrypted HDD.
i search for guide but what i found is for yubikey.

is it possible to apply this key to LUKS and if so, how to do it ?

**Comment by szszszsz** [comment]
See https://github.com/shimunn/fido2luks

**Comment by kagamineryuki** [comment]
> 
> 
> See https://github.com/shimunn/fido2luks

nice, thx for the suggestion. i'll try it out.

**Comment by nickray** [comment]
Also see https://github.com/solokeys/solo-python/pull/105

**Comment by saravanan30erd** [comment]
@kagamineryuki 

https://github.com/saravanan30erd/solokey-full-disk-encryption

It supports only Arch linux, but I can add support for other linux distros as well. which linux distro you are using?

**Comment by kagamineryuki** [comment]
> @kagamineryuki
> 
> https://github.com/saravanan30erd/solokey-full-disk-encryption
> 
> It supports only Arch linux, but I can add support for other linux distros as well. which linux distro you are using?

I'm currently using Fedora and Debian. Is it specifically solokeys or any FIDO2/U2F devices?

**Comment by saravanan30erd** [comment]
Is it specifically solokeys or any FIDO2/U2F devices?

It is created specifically for solokeys.
