### ISSUE TITLE
No clear documentation for self building

### ISSUE THREAD

**Issue by Semisol** [solokeys/solo#522]
Is there any documentation to make your own board and flash it, except the nucleo2 one?

**Comment by conorpp** [comment]
What do you mean by make your own board?  Like your own PCB?

**Comment by Semisol** [comment]
Yeah. A way to build your own key.

**Comment by conorpp** [comment]
you can find out hw source here: https://github.com/solokeys/solo-hw

As far as how to build your own PCB & assembly, it's out of scope for this repo.  You can find resources for how to do this, or use Kicad for example, all online.

**Comment by Semisol** [comment]
Oh okay.
