### ISSUE TITLE
fw 5.0.0 ?

### ISSUE THREAD

**Issue by slootsky** [solokeys/solo#533]
I received my solo hacker today, and it had firmware 5.0.0 on it.

I ran "solo key update" and it 'upgraded' it to v4.1.1

Should I be concerned, or just use it at 4.1.1?

**Comment by conorpp** [comment]
The "5.0.0" firmware is a fork of solokeys: https://github.com/conorpp/solo-dicekeys.

Please open issues on that repository.

The 4.1.1 firmware unfortunately does not have Dicekeys enabled, so you will need to program the 5.0.0 firmware back following this process: https://github.com/conorpp/solo-dicekeys/releases/tag/5.0.0.

**Comment by slootsky** [comment]
Thank you!!!

**Comment by aanno** [comment]
What about merge the changes from https://github.com/conorpp/solo-dicekeys into the official firmware and release a 4.2.0 or something?
