### ISSUE TITLE
SOMU firmware 5.0.0 availability?

### ISSUE THREAD

**Issue by jdeblese** [solokeys/solo#534]
I've just bricked a working somu by running "solo key update", which tried to upgrade my version 5.0.0 key with version 4.1.1 firmware. I can still get into DFU mode by pressing the button as I insert the key, but I don't see a version 5 of the firmware mentioned anywhere in the solo repo, and haven't found a somu-specific repo. Is the firmware I need to fix my key available somewhere here?

**Comment by jolo1581** [comment]
Maybe you should take a look to Issue 533.
Can be found in closed issues

**Comment by jdeblese** [comment]
Got it, thanks for the pointer! Forgot to check the closed issues as well.
