### ISSUE TITLE
STM32 BOOTLOADER - no driver

### ISSUE THREAD

**Issue by oomek** [solokeys/solo#550]
Bought the key on Amazon, Inserted into the usb port and no dice. Is the product faulty? Do I need to return it?

**Comment by oomek** [comment]
I bought this one:
https://www.amazon.co.uk/gp/product/B07ZWGQTXY/
Running on Windows 10

**Comment by oomek** [comment]
Tried solo-python and this is all I get:
```
C:\Users\Radek>solo ls
:: Solos

C:\Users\Radek>solo version
0.0.30
```

**Comment by nickray** [comment]
DFU mode sounds like there is no valid firmware on the device. Please contact hello@solokeys.com to get it replaced, thanks!

**Comment by oomek** [comment]
Brilliant :D Are those devices even tested before shipping?

**Comment by oomek** [comment]
Asked Amazon for a refund. Swapping for Yubikey.
