### ISSUE TITLE
Identification -- hacker or not?

### ISSUE THREAD

**Issue by tcal-x** [solokeys/solo#557]
How can I tell if I have a hacker version or not?   Would it be printed on the label on the electrostatic envelope?

I got these from a friend who has had them for a while and can't remember.   The labels have "US000155" (Solo Tap USB-A + NFC) and "US000168" (Somu).

Thanks!

**Comment by Zanthed** [comment]
Use solo-python and `solo key verify` and `solo key verify --pin ####`


See https://github.com/solokeys/solo/issues/471#issuecomment-695085031

**Comment by tcal-x** [comment]
Thanks @Zanthed !
