### ISSUE TITLE
Initial setup issue - Solokey is not responding - no lights

### ISSUE THREAD

**Issue by marcusmartinson** [solokeys/solo#569]
I just got my first Solokeys.. The first one was linked successfully to one of my online accounts, however the second one seems to be unresponsive or dead. I have tried to run a software update, but cannot get the key into boot-loader-mode pressing down the button and re-inserting the key. 

I can however see the key in the device manager in Windows (as STM32 BOOTLOADER) which tells me that the key is fine at least. 

Any advice would be much appreciated! 

Thanks!

**Comment by msiqx9** [comment]
Due to a manufacturing error, the key was not programmed.  You can programme it yourself as discussed in [#562](url).

**Comment by marcusmartinson** [comment]
Thank you.
