### ISSUE TITLE
Button automatically pressed on somu after upgrade to 4.1.3

### ISSUE THREAD

**Issue by lpapier** [solokeys/solo#578]
Hi,
I upgraded my somu key firmware from 4.1.2 to 4.1.3.

```
$ solo key update
Wrote temporary copy of firmware-4.1.3.json to /tmp/tmpjbpmszqt.json
sha256sums coincide: 102f69405e39b8491642215f59ee8ed26d490ab0d28a16f29f37047627c1939f
using signature version >2.5.3
erasing firmware...
updated firmware 100%             
time: 9.30 s
bootloader is verifying signature...
...pass!

Congratulations, your key was updated to the latest firmware version: 4.1.3
```
After the upgrade, I can still use the key but I don't need to press the button anymore. It's like the button is always pressed.

I get the same behavior connecting to a web site or with `solo key verify`. I'm asked to press the button, but it's automatically pressed.

```
$ solo key verify
Please press the button on your Solo key
Register valid
Valid Somu with firmware from SoloKeys.
```

I tried to downgrade to firmware 4.1.2 (`solo program bootloader firmware-4.1.2.json`), but the downgrade failed.

Laurent

**Comment by maweil** [comment]
I can confirm that this issue also happens on my Solo v1 (not somu) USB-A key after upgrading to 4.1.3.
When using an an SSH-key from my solo, I had to press the button before. Now it automatically authorizes each request.

**Comment by Erisa** [comment]
Same here with regular Solo v1, authorises every request with no prompt 😨

**Comment by conorpp** [comment]
Thanks for reporting!  My mistake with 4.1.3.
