### ISSUE TITLE
Can't use Solo V2 with Google

### ISSUE THREAD

**Issue by gavinbarron** [solokeys/solo#597]
Trying to add a new Solo V2 to my keys for Google and it fails with this message:

OS: Windows 11 Pro (Build 10.0.22000)
Browser: Chrome 97.0.4692.71 (Same result in Edge Dev)

![image](https://user-images.githubusercontent.com/7122716/149401625-6cb14ec0-17c2-4c21-8dd2-037f1aa95095.png)

Is there any way to get better diagnostics to help troubleshoot this issue?

Side note, it appears to work but fails with Microsoft Accounts but registered successfully for Twitter and GitHub.

**Comment by timcappalli** [comment]
Sorry it is unclear from your post since you mention both "for Google" and "with Microsoft Accounts". What is the relying party you're trying to register a credential on?

**Comment by gavinbarron** [comment]
Google.

**Comment by nickray** [comment]
Wrong repo. See also https://github.com/solokeys/solo2/discussions/96 and https://github.com/solokeys/fido-authenticator/pull/8.
