### ISSUE TITLE
Expect some minor disturbances as we migrate

### ISSUE THREAD

**Issue by nickray** [solokeys/solo#61]
Apologies for the noise:
- GitHub granted us the previously squatted solokeys namespaces, so we are moving to the organization https://github.com/solokeys (previous checkouts should work, please update your local `.git/config` files at your leisure)
- Technical documentation is moving to subpaths of docs.solokeys.io, so for instance this repository will have its documentation under https://docs.solokeys.io/solo/

**Comment by yparitcher** [comment]
please point travis-ci to the new repo to enable build checks, thanks
