### ISSUE TITLE
Metadata Statement

### ISSUE THREAD

**Issue by nickray** [solokeys/solo#89]
Let's prepare and publish a nice [metadata statement](https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#fido2-example)

There is [popular demand](https://twitter.com/alexseigler/status/1087922086335660033).

Open question is whether to register for [vendor ID](https://fidoalliance.org/certification/functional-certification/vendor-ids/vendor-id-request/), a cost of $3000 and prerequisite to [submit](https://fidoalliance.org/metadata/).

**Comment by 0x0ece** [comment]
I believe the first $3K are included in the certification costs. Let’s ask
the alliance first, but we need to know how much we have in the bank after
making Tap. Or at least this is what I understood.

-- 
Emanuele Cesena
emanuele.cesena@gmail.com

Check out my new security key: https://solokeys.com

**Comment by conorpp** [comment]
Here are the metadata statements for Solo for U2F and FIDO2

[Solo_metadata_statements.zip](https://github.com/solokeys/solo/files/2800277/Solo_metadata_statements.zip)

**Comment by nickray** [comment]
I committed these to https://github.com/solokeys/solo/tree/master/metadata and include them in https://docs.solokeys.io/solo/metadata-statements/

**Comment by merlokk** [comment]
maybe make separate page with root certificates?
